In [1]:
# pp.ipynb - preprocess count data and save into formatted adata files.

In [2]:
import anndata as ad
import numpy as np
import os
import pandas as pd
import scanpy as sc

In [3]:
spaceranger_fn = "/groups/cgsd/xianjie/projects/cna-benchmark/HCC3N_600spot/simulator_evaluation/base/gen_data/seed/spaceranger/HCC3N_600spot.spotxgene.h5ad"
starsolo_fn = "/groups/cgsd/xianjie/projects/cna-benchmark/HCC3N_600spot/simulator_evaluation/base/gen_data/seed/rdr_starsolo/HCC3N_600spot.spotxgene.starsolo.h5ad"
afc_fn = "/groups/cgsd/xianjie/projects/cna-benchmark/HCC3N_600spot/simulator_evaluation/base/gen_data/sccnasim/simu/2_afc/afc.counts.cell_anno.h5ad"

out_dir = "/groups/cgsd/xianjie/projects/cna-benchmark/HCC3N_600spot/simulator_evaluation/internal_consistency/seed_tools/pp"

In [4]:
normal_cell_type = "normal"

# Load Data

In [5]:
os.makedirs(out_dir, exist_ok = True)

### SpaceRanger

In [6]:
spaceranger = ad.read_h5ad(spaceranger_fn)
spaceranger

AnnData object with n_obs × n_vars = 600 × 33538
    obs: 'in_tissue', 'array_row', 'array_col', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'QC', 'x', 'y', 'selected', 'class', 'cell', 'cell_type'
    var: 'gene_ids', 'feature_types', 'genome', 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'feature'
    uns: 'QC_colors', 'class_colors', 'spatial'
    obsm: 'spatial'

In [7]:
spaceranger.obs

,in_tissue,array_row,array_col,n_genes_by_counts,total_counts,total_counts_mt,pct_counts_mt,QC,x,y,selected,class,cell,cell_type
0,1,50,102,3021,12693.0,1796.0,14.149531,Pass,102,27,Yes,QCPass_Selected,AAACAAGTATCTCCCA-1,normal
1,1,61,97,4567,23197.0,2442.0,10.527224,Pass,97,16,Yes,QCPass_Selected,AAACATTTCCCGGATT-1,normal
2,1,52,42,3413,15794.0,2507.0,15.873116,Pass,42,25,Yes,QCPass_Selected,AAACCGTTCGTCCAGG-1,normal
3,1,65,83,3746,18836.0,2082.0,11.053302,Pass,83,12,Yes,QCPass_Selected,AAACCTAAGCAGCCGG-1,normal
4,1,65,91,2223,7782.0,1119.0,14.379337,Pass,91,12,Yes,QCPass_Selected,AAACGGGCGTACGGGT-1,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,1,60,74,3605,16856.0,1689.0,10.020171,Pass,74,17,Yes,QCPass_Selected,TTGTGCAGCCACGTCA-1,normal
596,1,63,95,2195,7572.0,1049.0,13.853672,Pass,95,14,Yes,QCPass_Selected,TTGTGGTGGTACTAAG-1,normal
597,1,56,60,3760,19523.0,2076.0,10.633612,Pass,60,21,Yes,QCPass_Selected,TTGTGTATGCCACCAA-1,normal
598,1,51,59,2011,6501.0,827.0,12.721120,Pass,59,26,Yes,QCPass_Selected,TTGTGTTTCCCGAAAG-1,normal
599,1,58,42,3699,16884.0,1791.0,10.607677,Pass,42,19,Yes,QCPass_Selected,TTGTTTCACATCCAGG-1,normal

In [8]:
spaceranger.var

,gene_ids,feature_types,genome,mt,n_cells_by_counts,mean_counts,pct_dropout_by_counts,total_counts,feature
0,ENSG00000243485,Gene Expression,GRCh38,False,0,0.000000,100.000000,0.0,MIR1302-2HG
1,ENSG00000237613,Gene Expression,GRCh38,False,0,0.000000,100.000000,0.0,FAM138A
2,ENSG00000186092,Gene Expression,GRCh38,False,0,0.000000,100.000000,0.0,OR4F5
3,ENSG00000238009,Gene Expression,GRCh38,False,18,0.004197,99.580322,18.0,AL627309.1
4,ENSG00000239945,Gene Expression,GRCh38,False,0,0.000000,100.000000,0.0,AL627309.3
...,...,...,...,...,...,...,...,...,...
33533,ENSG00000277856,Gene Expression,GRCh38,False,0,0.000000,100.000000,0.0,AC233755.2
33534,ENSG00000275063,Gene Expression,GRCh38,False,0,0.000000,100.000000,0.0,AC233755.1
33535,ENSG00000271254,Gene Expression,GRCh38,False,30,0.007694,99.300536,33.0,AC240274.1
33536,ENSG00000277475,Gene Expression,GRCh38,False,0,0.000000,100.000000,0.0,AC213203.1
33537,ENSG00000268674,Gene Expression,GRCh38,False,0,0.000000,100.000000,0.0,FAM231C

In [9]:
spaceranger = spaceranger[:, ~spaceranger.var["feature"].duplicated(keep = False)].copy()
spaceranger.obs.index = spaceranger.obs["cell"]
spaceranger.var.index = spaceranger.var["feature"]
spaceranger

AnnData object with n_obs × n_vars = 600 × 33538
    obs: 'in_tissue', 'array_row', 'array_col', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'QC', 'x', 'y', 'selected', 'class', 'cell', 'cell_type'
    var: 'gene_ids', 'feature_types', 'genome', 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'feature'
    uns: 'QC_colors', 'class_colors', 'spatial'
    obsm: 'spatial'

### STARsolo

In [10]:
starsolo = ad.read_h5ad(starsolo_fn)
starsolo

/home/xianjie/.anaconda3/envs/SCSC/lib/python3.11/site-packages/anndata-0.10.7-py3.11.egg/anndata/_core/aligned_df.py:67: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

AnnData object with n_obs × n_vars = 600 × 33538
    obs: 'cell', 'cell_type'
    var: 'gene_id', 'gene', 'chrom', 'start', 'end', 'strand'

In [11]:
starsolo.var['feature'] = starsolo.var['gene']
starsolo = starsolo[:, ~starsolo.var["feature"].duplicated(keep = False)].copy()
starsolo.obs.index = starsolo.obs["cell"]
starsolo.var.index = starsolo.var["feature"]
starsolo

AnnData object with n_obs × n_vars = 600 × 33490
    obs: 'cell', 'cell_type'
    var: 'gene_id', 'gene', 'chrom', 'start', 'end', 'strand', 'feature'

### scCNASim afc

In [12]:
afc = ad.read_h5ad(afc_fn)
afc

/home/xianjie/.anaconda3/envs/SCSC/lib/python3.11/site-packages/anndata-0.10.7-py3.11.egg/anndata/_core/aligned_df.py:67: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

AnnData object with n_obs × n_vars = 600 × 32295
    obs: 'cell', 'cell_type'
    var: 'chrom', 'start', 'end', 'feature', 'strand'
    layers: 'A', 'B', 'U'

In [13]:
afc = afc[:, ~afc.var["feature"].duplicated(keep = False)].copy()
afc.X = afc.layers["A"] + afc.layers["B"] + afc.layers["U"]
afc = afc[afc.obs["cell_type"] == normal_cell_type, :].copy()
afc.obs.index = afc.obs["cell"]
afc.var.index = afc.var["feature"]
afc

AnnData object with n_obs × n_vars = 600 × 32295
    obs: 'cell', 'cell_type'
    var: 'chrom', 'start', 'end', 'feature', 'strand'
    layers: 'A', 'B', 'U'

### Use the same order of cells

In [14]:
spaceranger = spaceranger[afc.obs.index, :].copy()
spaceranger

AnnData object with n_obs × n_vars = 600 × 33538
    obs: 'in_tissue', 'array_row', 'array_col', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'QC', 'x', 'y', 'selected', 'class', 'cell', 'cell_type'
    var: 'gene_ids', 'feature_types', 'genome', 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'feature'
    uns: 'QC_colors', 'class_colors', 'spatial'
    obsm: 'spatial'

In [15]:
starsolo = starsolo[afc.obs.index, :].copy()
starsolo

AnnData object with n_obs × n_vars = 600 × 33490
    obs: 'cell', 'cell_type'
    var: 'gene_id', 'gene', 'chrom', 'start', 'end', 'strand', 'feature'

## Use intersect genes

In [16]:
adata_list = [spaceranger, starsolo, afc]

genes = None
for i, adata in enumerate(adata_list):
    if i == 0:
        genes = adata.var["feature"].to_numpy()
    else:
        genes = np.intersect1d(genes, adata.var["feature"])
genes.shape

(32272,)

### Use the same order of genes

In [17]:
afc = afc[:, afc.var["feature"].isin(genes)].copy()
print(afc)

spaceranger = spaceranger[:, afc.var.index].copy()
print(spaceranger)

starsolo = starsolo[:, afc.var.index].copy()
print(starsolo)

AnnData object with n_obs × n_vars = 600 × 32272
    obs: 'cell', 'cell_type'
    var: 'chrom', 'start', 'end', 'feature', 'strand'
    layers: 'A', 'B', 'U'
AnnData object with n_obs × n_vars = 600 × 32272
    obs: 'in_tissue', 'array_row', 'array_col', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'QC', 'x', 'y', 'selected', 'class', 'cell', 'cell_type'
    var: 'gene_ids', 'feature_types', 'genome', 'mt', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts', 'feature'
    uns: 'QC_colors', 'class_colors', 'spatial'
    obsm: 'spatial'
AnnData object with n_obs × n_vars = 600 × 32272
    obs: 'cell', 'cell_type'
    var: 'gene_id', 'gene', 'chrom', 'start', 'end', 'strand', 'feature'

# Save Data

### Check the order of cells and genes

In [18]:
assert np.all(spaceranger.obs["cell"].to_numpy() == afc.obs["cell"].to_numpy())
assert np.all(starsolo.obs["cell"].to_numpy() == afc.obs["cell"].to_numpy())

In [19]:
assert np.all(spaceranger.var["feature"].to_numpy() == afc.var["feature"].to_numpy())
assert np.all(starsolo.var["feature"].to_numpy() == afc.var["feature"].to_numpy())

In [20]:
spaceranger.var.index.name = None
starsolo.var.index.name = None
afc.var.index.name = None

In [21]:
spaceranger.write_h5ad(os.path.join(out_dir, "spaceranger.h5ad"), compression = 'gzip')
starsolo.write_h5ad(os.path.join(out_dir, "starsolo.h5ad"), compression = 'gzip')
afc.write_h5ad(os.path.join(out_dir, "afc.h5ad"), compression = 'gzip')