In [1]:
import numpy as np
import pandas as pd

In [2]:
raw_anno_fn = '/groups/cgsd/xianjie/projects/cna-benchmark/HCC3N_4289spot/base/data/cell_anno/HCC3.cell_manifest.txt'
sel_spot_fn = '/groups/cgsd/xianjie/projects/cna-benchmark/HCC3N_600spot/base/data/cell_anno/barcodes.tsv'
out_fn = '/groups/cgsd/xianjie/projects/cna-benchmark/HCC3N_600spot/base/data/cell_anno/spot_cluster.tsv'

In [3]:
anno = pd.read_csv(raw_anno_fn, sep = '\t')
anno

             comb.barcode sample.ident           barcode Cluster
0        AAACAGCTTTCAGAAG       cHC-1N  AAACAGCTTTCAGAAG     N.1
1        AAACAGGGTCTATATT       cHC-1N  AAACAGGGTCTATATT     N.5
2        AAACCGTTCGTCCAGG       cHC-1N  AAACCGTTCGTCCAGG     N.1
3        AAACCTCATGAAGTTG       cHC-1N  AAACCTCATGAAGTTG     N.1
4        AAACGAAGAACATACC       cHC-1N  AAACGAAGAACATACC     N.1
...                   ...          ...               ...     ...
84818  TTGTTTCACATCCAGG.3       HCC-5D  TTGTTTCACATCCAGG     D.2
84819  TTGTTTCATTAGTCTA.3       HCC-5D  TTGTTTCATTAGTCTA     D.4
84820  TTGTTTCCATACAACT.3       HCC-5D  TTGTTTCCATACAACT     D.2
84821    TTGTTTGTATTACACG       HCC-5D  TTGTTTGTATTACACG     D.4
84822  TTGTTTGTGTAAATTC.1       HCC-5D  TTGTTTGTGTAAATTC     D.1

[84823 rows x 4 columns]

In [4]:
anno.loc[anno['sample.ident'] == 'HCC-3N']['Cluster'].value_counts()

Cluster
N.1    2950
N.3     710
N.6     585
N.5      16
N.8      10
Name: count, dtype: int64

In [5]:
anno.loc[anno['sample.ident'] == 'HCC-3L']['Cluster'].value_counts()

Cluster
L.5    1423
L.1    1327
L.3    1095
L.6     841
L.8      64
Name: count, dtype: int64

In [6]:
anno.loc[anno['sample.ident'] == 'HCC-3T']['Cluster'].value_counts()

Cluster
T.2    2698
T.4    1610
T.7     127
T.6      12
Name: count, dtype: int64

In [7]:
anno = anno[anno['sample.ident'] == 'HCC-3N'].copy()
anno

           comb.barcode sample.ident           barcode Cluster
20234  AAACAAGTATCTCCCA       HCC-3N  AAACAAGTATCTCCCA     N.1
20235  AAACACCAATAACTGC       HCC-3N  AAACACCAATAACTGC     N.1
20236  AAACAGAGCGACTCCT       HCC-3N  AAACAGAGCGACTCCT     N.1
20237  AAACAGCTTTCAGAAG       HCC-3N  AAACAGCTTTCAGAAG     N.6
20238  AAACAGGGTCTATATT       HCC-3N  AAACAGGGTCTATATT     N.3
...                 ...          ...               ...     ...
24500  TTGTTTCACATCCAGG       HCC-3N  TTGTTTCACATCCAGG     N.1
24501  TTGTTTCATTAGTCTA       HCC-3N  TTGTTTCATTAGTCTA     N.1
24502  TTGTTTCCATACAACT       HCC-3N  TTGTTTCCATACAACT     N.1
24503  TTGTTTGTATTACACG       HCC-3N  TTGTTTGTATTACACG     N.1
24504  TTGTTTGTGTAAATTC       HCC-3N  TTGTTTGTGTAAATTC     N.1

[4271 rows x 4 columns]

In [8]:
sel = pd.read_csv(sel_spot_fn, header = None)
sel.columns = ['cell']
sel

                   cell
0    AAACAAGTATCTCCCA-1
1    AAACATTTCCCGGATT-1
2    AAACCGTTCGTCCAGG-1
3    AAACCTAAGCAGCCGG-1
4    AAACGGGCGTACGGGT-1
..                  ...
595  TTGTGCAGCCACGTCA-1
596  TTGTGGTGGTACTAAG-1
597  TTGTGTATGCCACCAA-1
598  TTGTGTTTCCCGAAAG-1
599  TTGTTTCACATCCAGG-1

[600 rows x 1 columns]

In [9]:
anno['cell'] = anno['barcode'] + '-1'
anno

,comb.barcode,sample.ident,barcode,Cluster,cell
20234,AAACAAGTATCTCCCA,HCC-3N,AAACAAGTATCTCCCA,N.1,AAACAAGTATCTCCCA-1
20235,AAACACCAATAACTGC,HCC-3N,AAACACCAATAACTGC,N.1,AAACACCAATAACTGC-1
20236,AAACAGAGCGACTCCT,HCC-3N,AAACAGAGCGACTCCT,N.1,AAACAGAGCGACTCCT-1
20237,AAACAGCTTTCAGAAG,HCC-3N,AAACAGCTTTCAGAAG,N.6,AAACAGCTTTCAGAAG-1
20238,AAACAGGGTCTATATT,HCC-3N,AAACAGGGTCTATATT,N.3,AAACAGGGTCTATATT-1
...,...,...,...,...,...
24500,TTGTTTCACATCCAGG,HCC-3N,TTGTTTCACATCCAGG,N.1,TTGTTTCACATCCAGG-1
24501,TTGTTTCATTAGTCTA,HCC-3N,TTGTTTCATTAGTCTA,N.1,TTGTTTCATTAGTCTA-1
24502,TTGTTTCCATACAACT,HCC-3N,TTGTTTCCATACAACT,N.1,TTGTTTCCATACAACT-1
24503,TTGTTTGTATTACACG,HCC-3N,TTGTTTGTATTACACG,N.1,TTGTTTGTATTACACG-1
24504,TTGTTTGTGTAAATTC,HCC-3N,TTGTTTGTGTAAATTC,N.1,TTGTTTGTGTAAATTC-1

In [10]:
np.sum(sel['cell'].isin(anno['cell']))

600

In [11]:
sel = sel.merge(anno[["cell", "Cluster"]], on = 'cell', how = 'left')
sel

                   cell Cluster
0    AAACAAGTATCTCCCA-1     N.1
1    AAACATTTCCCGGATT-1     N.1
2    AAACCGTTCGTCCAGG-1     N.1
3    AAACCTAAGCAGCCGG-1     N.1
4    AAACGGGCGTACGGGT-1     N.1
..                  ...     ...
595  TTGTGCAGCCACGTCA-1     N.1
596  TTGTGGTGGTACTAAG-1     N.1
597  TTGTGTATGCCACCAA-1     N.1
598  TTGTGTTTCCCGAAAG-1     N.1
599  TTGTTTCACATCCAGG-1     N.1

[600 rows x 2 columns]

In [12]:
sel['Cluster'].value_counts()

Cluster
N.1    535
N.3     46
N.6     18
N.8      1
Name: count, dtype: int64

In [13]:
sel.to_csv(out_fn, sep = '\t', header = False, index = False)